name: Code Formatting Check

on: [push, pull_request]

jobs:
  format-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Run on both Ubuntu and Windows

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install black flake8

      - name: Run Black
        run: |
          black .

      - name: Run Flake8 with Custom Config
        run: |
          flake8 --config=.flake8
